- name: Tinyproxy for Ubuntu server
  block:

  - name: Add tinyproxy group 
    group:
      name: tinyproxy
      state: present
    
  - name: Add tinyproxy user
    user:
      name: tinyproxy
      state: present
      group: tinyproxy
    
  - name: Install tinyproxy on the proxy server
    apt:
      name: tinyproxy
      state: latest

  - name: Ensure tinyproxy is stopped
    systemd:
      name: tinyproxy
      state: stopped

  - name: Templating /etc/tinyproxy.conf
    template:
      src: tinyproxy.conf.j2
      dest: /etc/tinyproxy.conf
    notify: Reload tinyproxy

  - name: Ensure tinyproxy is running
    systemd:
      name: tinyproxy
      state: started

  when: ansible_distribution == "Ubuntu"
